apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      tier: backend
  template:
    metadata:
      labels:
        app: webapp
        tier: backend
    spec:
      containers:
      - name: webapp
        image: chathuradandeniyaa/webapp:1.1.1
        ports:
        - containerPort: 3000